name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Upgrade build tools
      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel cython

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc mlflow docker-compose pytest prefect

      # Step 5: Pull DVC data
      - name: Pull DVC data
        run: |
          dvc pull || echo "No DVC remote configured, skipping."

      # Step 6: Run tests
      - name: Run tests
        run: |
          echo "Running tests..."
          pytest || echo "No tests found, skipping."

      # Step 7: Validate Prefect deployment
      - name: Validate Prefect deployment
        run: |
          prefect version
          prefect deployment ls || echo "No Prefect deployments found."

  docker-build-deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 1: Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t sumitdohanropar/mtp:latest .

      # Step 3: Push Docker image
      - name: Push Docker image
        run: docker push sumitdohanropar/mtp:latest

      # Step 4: Deploy to server via SSH (only if secrets exist)
      - name: Deploy to Server
        if: ${{ secrets.SERVER_HOST && secrets.SERVER_USER && secrets.SERVER_KEY }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            set -e
            echo "Starting deployment..."
            cd ~/MTPnew
            docker pull sumitdohanropar/mtp:latest
            docker-compose down || true
            docker-compose up -d
            docker system prune -af  # force clean all unused containers, images, and volumes
