name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc mlflow docker-compose pytest

      # Step 4: Pull DVC data
      - name: Pull DVC data
        run: |
          dvc pull || echo "No remote configured"

      # Step 5: Run tests
      - name: Run tests
        run: |
          echo "Running tests..."
          pytest || echo "No tests found, skipping."

  docker-build-deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 1: Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t sumitdohanropar/mtp:latest .

      # Step 3: Push Docker image
      - name: Push Docker image
        run: docker push sumitdohanropar/mtp:latest

      # Step 4: Deploy on your server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/MTPnew
            docker pull sumitdohanropar/mtp:latest
            docker-compose down
            docker-compose up -d
